// <auto-generated />
using System;
using LuisJose_AP1_P2.Server.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LuisJose_AP1_P2.Server.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.13");

            modelBuilder.Entity("LuisJose_AP1_P2.Shared.Entradas", b =>
                {
                    b.Property<int>("EntradaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CantidadProducida")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Concepto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("EntradaID");

                    b.ToTable("Entradas");
                });

            modelBuilder.Entity("LuisJose_AP1_P2.Shared.EntradasDetalle", b =>
                {
                    b.Property<int>("DetalleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CantidadUtilizada")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EntradaID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductoID")
                        .HasColumnType("INTEGER");

                    b.HasKey("DetalleID");

                    b.HasIndex("EntradaID");

                    b.ToTable("EntradasDetalle");
                });

            modelBuilder.Entity("LuisJose_AP1_P2.Shared.Productos", b =>
                {
                    b.Property<int>("ProductoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripción")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Existencia")
                        .HasColumnType("INTEGER");

                    b.Property<double>("PrecioCompra")
                        .HasColumnType("REAL");

                    b.Property<double>("PrecioVenta")
                        .HasColumnType("REAL");

                    b.HasKey("ProductoID");

                    b.ToTable("Productos");

                    b.HasData(
                        new
                        {
                            ProductoID = 1,
                            Descripción = "Maní",
                            Existencia = 250,
                            PrecioCompra = 8.0,
                            PrecioVenta = 15.0
                        },
                        new
                        {
                            ProductoID = 2,
                            Descripción = "Pistachos",
                            Existencia = 300,
                            PrecioCompra = 15.0,
                            PrecioVenta = 30.0
                        },
                        new
                        {
                            ProductoID = 3,
                            Descripción = "Pasas",
                            Existencia = 130,
                            PrecioCompra = 10.0,
                            PrecioVenta = 25.0
                        },
                        new
                        {
                            ProductoID = 4,
                            Descripción = "Ciruelas",
                            Existencia = 350,
                            PrecioCompra = 25.0,
                            PrecioVenta = 50.0
                        },
                        new
                        {
                            ProductoID = 5,
                            Descripción = "Mixto MPP",
                            Existencia = 320,
                            PrecioCompra = 30.0,
                            PrecioVenta = 60.0
                        },
                        new
                        {
                            ProductoID = 6,
                            Descripción = "Mixto MPC",
                            Existencia = 310,
                            PrecioCompra = 30.0,
                            PrecioVenta = 60.0
                        },
                        new
                        {
                            ProductoID = 7,
                            Descripción = "Mixto MPP",
                            Existencia = 250,
                            PrecioCompra = 25.0,
                            PrecioVenta = 50.0
                        });
                });

            modelBuilder.Entity("LuisJose_AP1_P2.Shared.EntradasDetalle", b =>
                {
                    b.HasOne("LuisJose_AP1_P2.Shared.Entradas", null)
                        .WithMany("entradasDetalle")
                        .HasForeignKey("EntradaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LuisJose_AP1_P2.Shared.Entradas", b =>
                {
                    b.Navigation("entradasDetalle");
                });
#pragma warning restore 612, 618
        }
    }
}
